'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { api, ApiError, errorMessage } from '@/lib/api';
import { EmailPreviewPane } from '@/components/email-preview';
import { Glyph } from '@/components/icons';
import { extractTemplateVariables } from '@/lib/template-variables';
import {
  Alert,
  Button,
  Card,
  Field,
  IconButton,
  Input,
  PageHeader,
  Select,
  Textarea,
  VariableChip,
} from '@/components/ui';
import type { EmailPreview, EmailTemplate, TemplateStatus } from '@/lib/types';

type BodyType = 'html' | 'text';

/**
 * Whether a stored HTML body is the wrapper generated from plain text.
 *
 * Used only to decide which tab a saved template opens on. It is a heuristic,
 * not a source of truth -- the stored HTML is shown regardless, so a wrong
 * guess costs a click rather than any content.
 */
function looksGenerated(html: string): boolean {
  return (
    html.includes('max-width:600px;margin:0 auto;background:#ffffff;border-radius:12px;') &&
    html.includes('padding:28px;font-size:15px;line-height:24px;color:#374151;')
  );
}

export function TemplateEditor({ template }: { template?: EmailTemplate }) {
  const router = useRouter();
  const htmlFileRef = useRef<HTMLInputElement>(null);
  const textFileRef = useRef<HTMLInputElement>(null);

  const [name, setName] = useState(template?.name ?? '');
  const [description, setDescription] = useState(template?.description ?? '');
  const [subject, setSubject] = useState(template?.subject ?? '');
  const [htmlContent, setHtmlContent] = useState(template?.htmlContent ?? '');
  const [textContent, setTextContent] = useState(template?.textContent ?? '');
  const [status, setStatus] = useState<TemplateStatus>(template?.status ?? 'DRAFT');

  /**
   * Which body is authored, or `''` until it has been chosen. The other half is
   * generated by the server, so a message always ships both parts whichever is
   * picked here.
   *
   * A new template starts unselected rather than defaulting to HTML: nothing is
   * prefilled, so there is no body to show and no basis for guessing which one
   * the author wants. The body editor appears once the choice is made.
   *
   * A saved template is opened in the mode it was written in. There is no
   * stored flag for that, so it is inferred: a body whose HTML is the generated
   * wrapper was authored as text. The marker is the wrapper's own comment-free
   * signature, and when the guess is wrong the worst case is opening on the
   * HTML tab, which shows the real stored body either way.
   */
  const [bodyType, setBodyType] = useState<BodyType | ''>(
    template ? (looksGenerated(template.htmlContent) ? 'text' : 'html') : '',
  );

  /**
   * What is currently on the server, for the unsaved-changes check.
   *
   * It has to move when a save succeeds: comparing against the `template` prop
   * would keep reporting the form as dirty after saving, and Back would nag
   * about changes that are already stored.
   */
  const savedRef = useRef({
    name: template?.name ?? '',
    description: template?.description ?? '',
    subject: template?.subject ?? '',
    htmlContent: template?.htmlContent ?? '',
    textContent: template?.textContent ?? '',
    status: (template?.status ?? 'DRAFT') as TemplateStatus,
  });

  // Recomputed as the body is typed, so the chips are never stale against the
  // textarea the author is looking at.
  const variables = useMemo(
    // Only the authored body counts: the other is generated from it, so
    // including it would list the same names twice over.
    () =>
      extractTemplateVariables(
        subject,
        bodyType === 'html' ? htmlContent : bodyType === 'text' ? textContent : '',
      ),
    [subject, bodyType, htmlContent, textContent],
  );

  const [preview, setPreview] = useState<EmailPreview | null>(null);
  const [previewing, setPreviewing] = useState(false);
  const [previewFull, setPreviewFull] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({});

  async function handlePreview() {
    // Nothing written yet. Without this the request goes up with an empty body
    // and comes back as "Request validation failed", which describes the API
    // contract rather than the thing the author still has to do.
    const authored = bodyType === 'html' ? htmlContent : bodyType === 'text' ? textContent : '';
    if (!authored.trim()) {
      setError('Template not uploaded or created. Please upload or create a template.');
      return;
    }

    setPreviewing(true);
    setError(null);
    try {
      setPreview(
        await api.post<EmailPreview>('/preview', {
          subject: subject || '(no subject)',
          // Only the authored half is sent, exactly as on save: the server
          // derives the other one, so the preview is of the message that would
          // actually ship rather than of a stale body left in the other box.
          htmlContent: bodyType === 'html' ? htmlContent : undefined,
          textContent: bodyType === 'text' ? textContent : undefined,
        }),
      );
    } catch (caught) {
      setError(errorMessage(caught));
    } finally {
      setPreviewing(false);
    }
  }

  /** Shared by both importers; only the destination differs. */
  function importInto(
    event: React.ChangeEvent<HTMLInputElement>,
    apply: (contents: string) => void,
  ) {
    const input = event.target;
    const file = input.files?.[0];
    if (!file) return;

    if (file.size > 2_000_000) {
      setError(`${file.name} is larger than 2 MB.`);
      input.value = '';
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      apply(String(reader.result ?? ''));
      setNotice(`Imported ${file.name}.`);
      // Cleared so re-picking the same file fires `change` again.
      input.value = '';
    };
    reader.onerror = () => {
      setError('Could not read that file.');
      input.value = '';
    };
    reader.readAsText(file);
  }

  async function handleSave(event: React.FormEvent) {
    event.preventDefault();
    setError(null);
    setNotice(null);
    setFieldErrors({});

    // Both bodies would go up empty otherwise, and the API would reject it with
    // a message about the HTML body rather than the choice that is missing.
    if (!bodyType) {
      setError('Choose a template type before saving.');
      return;
    }

    setSaving(true);

    const body = {
      name: name.trim(),
      description: description.trim() || undefined,
      subject: subject.trim(),
      // Only the authored body is sent. The empty string on the other one is
      // meaningful to the API: it means "regenerate this from the one I did
      // write", so switching an existing template between modes replaces the
      // stale half rather than leaving it behind.
      htmlContent: bodyType === 'html' ? htmlContent : '',
      textContent: bodyType === 'text' ? textContent : '',
      status,
    };

    try {
      if (template) {
        // Editing stays put: you usually want to keep working on the body.
        await api.put<EmailTemplate>(`/templates/${template.id}`, body);
        savedRef.current = {
          name: name.trim(),
          description,
          subject: subject.trim(),
          htmlContent,
          textContent,
          status,
        };
        setNotice('Template saved.');
        router.refresh();
      } else {
        const created = await api.post<EmailTemplate>('/templates', body);
        // Creating returns to the table, where the new template is listed
        // first. The name rides along so the list can confirm what happened.
        router.push(`/templates?created=${encodeURIComponent(created.name)}`);
      }
    } catch (caught) {
      if (caught instanceof ApiError) setFieldErrors(caught.fieldErrors);
      setError(errorMessage(caught));
    } finally {
      setSaving(false);
    }
  }

  useEffect(() => {
    if (!previewFull) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setPreviewFull(false);
    };
    document.addEventListener('keydown', onKeyDown);
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKeyDown);
      document.body.style.overflow = previousOverflow;
    };
  }, [previewFull]);

  function goBack() {
    // Leaving a half-written template asks once. Compared against what is
    // stored rather than against a dirty flag, so retyping a value back to what
    // it was does not count as a change.
    const saved = savedRef.current;
    const dirty =
      name.trim() !== saved.name ||
      description !== saved.description ||
      subject.trim() !== saved.subject ||
      htmlContent !== saved.htmlContent ||
      textContent !== saved.textContent ||
      status !== saved.status;

    if (dirty && !confirm('Leave without saving? Your changes will be lost.')) return;
    router.push('/templates');
  }

  return (
    <form onSubmit={handleSave}>
      <PageHeader
        title={template ? `Edit ${template.name}` : 'New template'}
        description="Use {{variable}} for personalisation, with {{variable | fallback}} for a default."
        actions={
          <>
            {/* Back sits first and reads as a word, not a bare arrow: leaving a
                half-written template is a decision, and it should be obvious
                which control does it. `push` rather than `router.back()` --
                this page is reachable from places other than the list. */}
            <Button type="button" variant="secondary" onClick={goBack}>
              <Glyph name="back" />
              Back to templates
            </Button>
            <Button type="button" variant="secondary" onClick={handlePreview} loading={previewing}>
              Preview
            </Button>
            <Button type="submit" loading={saving}>
              {template ? 'Save changes' : 'Create template'}
            </Button>
          </>
        }
      />

      {error && (
        <div className="mb-4">
          <Alert tone="error" onDismiss={() => setError(null)}>
            {error}
          </Alert>
        </div>
      )}
      {notice && (
        <div className="mb-4">
          <Alert tone="success" onDismiss={() => setNotice(null)}>
            {notice}
          </Alert>
        </div>
      )}

      <div className="grid gap-5 sm:gap-6 xl:grid-cols-2">
        <div className="min-w-0 space-y-5 sm:space-y-6">
          <Card title="Details" collapsible>
            <div className="space-y-4">
              <Field label="Template name" htmlFor="name" error={fieldErrors['name']} required>
                <Input
                  id="name"
                  value={name}
                  onChange={(event) => setName(event.target.value)}
                  required
                  maxLength={150}
                  placeholder="Merchant announcement"
                />
              </Field>

              <Field label="Description" htmlFor="description">
                <Input
                  id="description"
                  value={description}
                  onChange={(event) => setDescription(event.target.value)}
                  maxLength={1000}
                  placeholder="Optional note for your team"
                />
              </Field>

              <Field
                label="Default subject"
                htmlFor="subject"
                error={fieldErrors['subject']}
                hint="Can be overridden per campaign. Variables work here too."
                required
              >
                <Input
                  id="subject"
                  value={subject}
                  onChange={(event) => setSubject(event.target.value)}
                  required
                  maxLength={500}
                  placeholder="A quick update for {{store_name | your store}}"
                />
              </Field>

              <Field
                label="Template type"
                htmlFor="bodyType"
                hint={
                  bodyType === 'html'
                    ? 'Write HTML. A plain-text alternative is generated from it.'
                    : bodyType === 'text'
                      ? 'Write plain text. An HTML version is generated from it.'
                      : 'Pick how to write the body. The editor opens once you choose.'
                }
              >
                <Select
                  id="bodyType"
                  value={bodyType}
                  required
                  onChange={(event) => setBodyType(event.target.value as BodyType)}
                >
                  {/* `disabled`, so this is the starting state but not somewhere
                      the author can return to -- there is no body to show while
                      no type is chosen. */}
                  <option value="" disabled>
                    Select a type
                  </option>
                  <option value="html">HTML body</option>
                  <option value="text">Plain text body</option>
                </Select>
              </Field>

              <Field label="Status" htmlFor="status" hint="Only active templates can be used in a campaign.">
                <Select
                  id="status"
                  value={status}
                  onChange={(event) => setStatus(event.target.value as TemplateStatus)}
                >
                  <option value="DRAFT">Draft</option>
                  <option value="ACTIVE">Active</option>
                  <option value="INACTIVE">Inactive</option>
                </Select>
              </Field>

              {/* Here rather than in the templates table: the list is a place to
                  find a template, but this is where the variables are actually
                  authored, and seeing them appear as you type is what catches a
                  typo like {{stor_name}} before a campaign renders it blank. */}
              <div className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
                  <p className="text-xs font-semibold text-slate-700">
                    Variables in this template
                  </p>
                  <p className="text-2xs text-slate-400">from the subject and the body</p>
                </div>

                {variables.length === 0 ? (
                  <p className="mt-2 text-xs leading-relaxed text-slate-500">
                    None yet. Write{' '}
                    <code className="rounded bg-white px-1 py-0.5 font-mono text-2xs text-slate-700">
                      {'{{first_name | there}}'}
                    </code>{' '}
                    in the subject or body to personalise it — the part after{' '}
                    <code className="font-mono">|</code> is used when a recipient has no value.
                  </p>
                ) : (
                  <>
                    <div className="mt-2 flex flex-wrap gap-1.5">
                      {variables.map((variable) => (
                        <VariableChip key={variable} name={variable} braces />
                      ))}
                    </div>
                    <p className="mt-2 text-2xs leading-relaxed text-slate-500">
                      Every recipient needs a value for these, or a{' '}
                      <code className="font-mono">| fallback</code>. Unsubscribe links are added
                      automatically and are not listed.
                    </p>
                  </>
                )}
              </div>
            </div>
          </Card>

          {bodyType === 'html' ? (
            <Card
              title="HTML body"
              description="Kept exactly as written; only the dashboard preview is sanitised. A plain-text alternative is generated from it."
              actions={
                <>
                  <input
                    ref={htmlFileRef}
                    type="file"
                    accept=".html,.htm,text/html"
                    onChange={(event) => importInto(event, setHtmlContent)}
                    className="hidden"
                    id="import-html"
                  />
                  <Button
                    type="button"
                    size="sm"
                    variant="secondary"
                    onClick={() => htmlFileRef.current?.click()}
                  >
                    Import .html
                  </Button>
                </>
              }
            >
              <Textarea
                value={htmlContent}
                onChange={(event) => setHtmlContent(event.target.value)}
                rows={18}
                spellCheck={false}
                required
                aria-label="HTML body"
                invalid={Boolean(fieldErrors['htmlContent'])}
                placeholder={'<p>Hi {{first_name | there}},</p>'}
                className="text-xs leading-relaxed sm:min-h-[28rem]"
              />
              {fieldErrors['htmlContent'] && (
                <p className="mt-1 text-xs font-medium text-red-600">
                  {fieldErrors['htmlContent']}
                </p>
              )}
            </Card>
          ) : bodyType === 'text' ? (
            <Card
              title="Plain-text body"
              description="Written as text. An HTML part is generated from it, so the message still ships both."
              actions={
                <>
                  <input
                    ref={textFileRef}
                    type="file"
                    accept=".txt,.text,text/plain"
                    onChange={(event) => importInto(event, setTextContent)}
                    className="hidden"
                    id="import-text"
                  />
                  <Button
                    type="button"
                    size="sm"
                    variant="secondary"
                    onClick={() => textFileRef.current?.click()}
                  >
                    Import .txt
                  </Button>
                </>
              }
            >
              <Textarea
                value={textContent}
                onChange={(event) => setTextContent(event.target.value)}
                rows={18}
                spellCheck
                required
                aria-label="Plain text body"
                invalid={Boolean(fieldErrors['htmlContent'])}
                placeholder={'Hi {{first_name | there}},\n\nA blank line starts a new paragraph.'}
                className="text-xs leading-relaxed sm:min-h-[28rem]"
              />
              {fieldErrors['htmlContent'] && (
                <p className="mt-1 text-xs font-medium text-red-600">
                  {fieldErrors['htmlContent']}
                </p>
              )}
            </Card>
          ) : null}
        </div>

        <div className="min-w-0 xl:sticky xl:top-6 xl:self-start">
          <Card
            title="Preview"
            actions={
              <IconButton
                label="Expand preview to full screen"
                onClick={() => setPreviewFull(true)}
              >
                <Glyph name="expand" />
              </IconButton>
            }
          >
            <EmailPreviewPane preview={preview} loading={previewing} />
          </Card>
        </div>
      </div>

      {/* Full-screen preview.
          Rendered as a sibling of the grid rather than inside the Preview card,
          because a `position: fixed` child of a `sticky` ancestor is positioned
          against that ancestor rather than the viewport -- it would fill the
          column, not the screen. */}
      {previewFull && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Email preview"
          className="fixed inset-0 z-50 flex animate-fade-in flex-col bg-[#F5F7FA]"
        >
          <div className="flex shrink-0 items-center justify-between gap-3 border-b border-slate-200 bg-white px-4 py-3 sm:px-5">
            <div className="min-w-0">
              <h2 className="truncate text-base font-bold text-slate-900">Preview</h2>
              <p className="mt-[3px] truncate text-xs text-slate-500">
                {subject || 'No subject yet'}
              </p>
            </div>
            <div className="flex shrink-0 items-center gap-2">
              <Button
                type="button"
                size="sm"
                variant="secondary"
                onClick={handlePreview}
                loading={previewing}
              >
                Refresh
              </Button>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                onClick={() => setPreviewFull(false)}
              >
                <Glyph name="collapse" />
                Exit full screen
              </Button>
            </div>
          </div>

          <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">
            <EmailPreviewPane preview={preview} loading={previewing} fill />
          </div>
        </div>
      )}
    </form>
  );
}
